apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: dccn-tendermint
  labels:
    app: dccn-tendermint
spec:
  externalTrafficPolicy: Local
  selector:
    app: dccn-tendermint
  type: LoadBalancer
  ports:
  - name: p2p-1
    port: 20016
    targetPort: 26656
  - name: p2p-2
    port: 20026
    targetPort: 26656
  - name: p2p-3
    port: 20036
    targetPort: 26656
  - name: p2p-4
    port: 20046
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657
  - name: http
    port: 80
    targetPort: 26657
  - name: https
    port: 443
    targetPort: 26657

---
apiVersion: v1
kind: Service
metadata:
  name: tendermint-1
  labels:
    app: tendermint-1
spec:
  selector:
    id: tendermint-1
  ports:
  - name: p2p-1
    port: 26656
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657


---
apiVersion: v1
kind: Service
metadata:
  name: tendermint-2
  labels:
    app: tendermint-2
spec:
  selector:
    id: tendermint-2
  ports:
  - name: p2p-2
    port: 26656
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657


---
apiVersion: v1
kind: Service
metadata:
  name: tendermint-3
  labels:
    app: tendermint-3
spec:
  selector:
    id: tendermint-3
  ports:
  - name: p2p-3
    port: 26656
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657


---
apiVersion: v1
kind: Service
metadata:
  name: tendermint-4
  labels:
    app: tendermint-4
spec:
  selector:
    id: tendermint-4
  ports:
  - name: p2p-4
    port: 26656
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657

