apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: ankr-chain
  labels:
    app: ankr-chain
spec:
  externalTrafficPolicy: Local
  selector:
    app: ankr-chain
  type: LoadBalancer
  ports:
  - name: p2p-1
    port: 20016
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657
  - name: http
    port: 80
    targetPort: 26657
  - name: https
    port: 443
    targetPort: 26657

---
apiVersion: v1
kind: Service
metadata:
  name: ankrchain-1
  labels:
    app: ankrchain-1
spec:
  selector:
    id: ankrchain-1
  ports:
  - name: p2p-1
    port: 26656
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657

