apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-ankrchain-1-3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
